### ISSUE TITLE
Calculate CAN bus load on each bus

### ISSUE THREAD

**Issue by caljay98** [gopher-motorsports/power-logging-module-23#6]
The PLM should calculate the load on each CAN bus and log it. You might have to do some modifications to the GCAN library, like maybe the lib will store how many new messages/bits it has received in the last XXXms. I would recommend doing some research on how other devices and companies do this and just copy them if it makes sense.

For logging, it would likely be easiest to have a GCAN parameter defined that is the CAN bus load for each bus, and then log it like you would any parameter

**Comment by olale013** [comment]
Use `__weak void HAL_CAN_RxFifo0MsgPendingCallback`. Log number of interrupts/time. Gives an upper bound on total bytes transferred (some messages don't have full data fields, some are std IDs, etc).
